# Factorization and other fun

## Factorization

### LU factorization

$ PA = LU $

In [19]:
# Toy linear system
A = randn(3,3)
x = ones(3)
b = A * x

3-element Vector{Float64}:
 -0.06125979233212009
 -2.2449260233675306
 -0.7046062694310072

We may perform an LU factorization with the function `lu`.

In [15]:
using LinearAlgebra
Alu = lu(A)
typeof(Alu)

LU{Float64, Matrix{Float64}, Vector{Int64}}

To access the permutation matrix `P`, the lower triangular unit diagonal matrix `L`, or the upper triangular matrix `U`, we use:

In [16]:
Alu.P

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  0.0  1.0
 0.0  1.0  0.0

In [17]:
Alu.L

3×3 Matrix{Float64}:
 1.0        0.0       0.0
 0.136611   1.0       0.0
 0.959352  -0.904621  1.0

In [18]:
Alu.U

3×3 Matrix{Float64}:
 0.569668  1.25359  -1.18415
 0.0       1.63823  -0.537279
 0.0       0.0       0.616504

We can solve the linear system using either the original matrix or the factorization object.

In [ ]:
A\b